### ISSUE TITLE
'NoneType' object has no attribute 'damage'

### ISSUE THREAD

**Issue by Ragowit** [danielyule/hearthbreaker#111]
Deck 1: Deathlord, Mad Scientist, Darkscale Healer, Silverback Patriarch, Novice Engineer, Shattered Sun Cleric, Ship's Cannon, Harvest Golem, Frost Elemental, Dragonling Mechanic, Water Elemental, River Crocolisk, War Golem, Frostwolf Warlord, Silvermoon Guardian, Nerubian Egg, Tinkmaster Overspark, Micro Machine, Frostwolf Warlord, Stormpike Commando, Silvermoon Guardian, Frostwolf Grunt, Kel'Thuzad, Flamecannon, Wisp, Murloc Raider, Chillwind Yeti, Defender of Argus, Razorfen Hunter, River Crocolisk

Deck 2: Spellbreaker, Lost Tallstrider, Mind Control Tech, Gahz'rilla, Mogu'shan Warden, Sylvanas Windrunner, Steamwheedle Sniper, King of Beasts, Core Hound, Tundra Rhino, Novice Engineer, Frost Elemental, Shattered Sun Cleric, Haunted Creeper, Wailing Soul, Antique Healbot, Dire Wolf Alpha, Cobra Shot, Haunted Creeper, Nightblade, Shieldbearer, Fen Creeper, Tauren Warrior, Ogre Brute, Cobra Shot, Twilight Drake, Leper Gnome, Foe Reaper 4000, Ogre Magi, Gadgetzan Auctioneer

```
Traceback (most recent call last):
  File "C:\Users\Ragowit\Documents\GitHub\mcts\hearthbreaker\uct.py", line 172, in DoMove
    self.game.current_player.hero.power.use()
  File "C:\Users\Ragowit\Documents\GitHub\mcts\hearthbreaker\hearthbreaker\powers.py", line 32, in use
    target.damage(2 * self.hero.player.spell_multiplier, None)
AttributeError: 'NoneType' object has no attribute 'damage'
```

**Comment by Ragowit** [comment]
Again.

Deck 1: Fireball, Duplicate, Darkscale Healer, Silverback Patriarch, Novice Engineer, Shattered Sun Cleric, Ship's Cannon, Harvest Golem, Frost Elemental, Dragonling Mechanic, Water Elemental, River Crocolisk, War Golem, Frostwolf Warlord, Silvermoon Guardian, Nerubian Egg, Tinkmaster Overspark, Micro Machine, Frostwolf Warlord, Stormpike Commando, Silvermoon Guardian, Frostwolf Grunt, Kel'Thuzad, Flamecannon, Wisp, Murloc Raider, Chillwind Yeti, Defender of Argus, Razorfen Hunter, River Crocolisk

Deck 2: Grimscale Oracle, Oasis Snapjaw, Captain's Parrot, Gurubashi Berserker, Foe Reaper 4000, Bluegill Warrior, Cogmaster, King Krush, Big Game Hunter, Silvermoon Guardian, Injured Blademaster, Lil' Exorcist, Dread Corsair, Glaivezooka, Scavenging Hyena, Stormwind Knight, Frostwolf Warlord, Lost Tallstrider, Glaivezooka, Wisp, Oasis Snapjaw, Ancient Brewmaster, Mad Bomber, Antique Healbot, Gnomeregan Infantry, Mini-Mage, Deathwing, Bloodsail Corsair, Mechanical Yeti, Steamwheedle Sniper

**Comment by danielyule** [comment]
The problem seems to be Steamwheedle Sniper.  The line your error gives for powers.py is not the line it has on my copy, and hasn't been since early March.  I'm wondering if you have an outdated copy of this file, perhaps?

Anyways, the problem is coming from not choosing a proper target for the hunter's hero power.  Is there something in your code related to choosing hero powers that you wouldn't have doing anything if it's not mage or priest?

**Comment by Ragowit** [comment]
Ah, I guess you nailed it. My code only cares about targeting if it's a mage or priest. Didn't think about that. I'll close this issue.
