### ISSUE TITLE
Boom Bots and Flame Leviathan

### ISSUE THREAD

**Issue by tokkot** [danielyule/hearthbreaker#113]
I noticed that if one player plays Dr. Boom and passes the turn, and then the other player draws into a Flame Leviathan, the Boom Bots explode and damage their owner.

**Comment by randomflyingtaco** [comment]
Made a test to check this.  Flame Leviathan deals 2 damage to all characters, including both heroes.  My test is as follows:
    def test_BoomBug(self):
        game = generate_game_for(DoctorBoom, FlameLeviathan, OneCardPlayingAgent, OneCardPlayingAgent)
        game.players[0].max_mana = 7

        for turn in range(0, 2):
            game.play_single_turn()
            
        self.assertEqual(1, len(game.players[0].minions))
        self.assertEqual(7, game.players[0].minions[0].calculate_attack())
        self.assertEqual(5, game.players[0].minions[0].health)
        self.assertEqual(28, game.players[0].hero.health)  # 2 damage from Flame Levi
        self.assertEqual(24, game.players[1].hero.health)  # 2 damage from FLame Levi and 4 from Boom Bots

If you have a case where player 0 takes more than 2 damage, please post it.

**Comment by tokkot** [comment]
Your test seems to work, so perhaps the bug is coming from my code wherein I try to manipulate who goes first in a game. So what is the correct way to do that? I notice that `generate_game_for` tries to fix the turn order, but fails:

    def test_TurnOrder(self):
        game = generate_game_for(DoctorBoom, FlameLeviathan, OneCardPlayingAgent, OneCardPlayingAgent)
        game.players[0].max_mana = 7      
        game.play_single_turn()
                
        self.assertEqual(1, len(game.current_player.minions))

**Comment by Ragowit** [comment]
```play_single_turn``` plays one turn for one player. I'm not at home so I'm a little bit uncertain on who current_player is currently pointing at, but the assert should return either 3 (players[0] with Boom + 2 Bots) or 0 (players[1] with no minions). So yeah, ```self.assertEqual(1, len(game.current_player.minions))``` will, and should, fail.

You seem to expect that the second player have already drawn a card perhaps? This isn't the case. A player starts it turn, and play it through, in one ```play_single_turn```.

**Comment by tokkot** [comment]
Good point, I didn't think out my example. Actually I'm pretty sure that the bug had something to do with the odd way I was making stacked decks... Once I use the `StackedDeck` function instead of trying to do it by hand, the problem goes away. Thanks
