### ISSUE TITLE
'Hero' object has no attribute 'weapon'

### ISSUE THREAD

**Issue by sayginburak** [danielyule/hearthbreaker#114]
I run text_runney.py and select cards with space and then press enter, program closed and it gives this error

'Hero' object has no attribute 'weapon'

Shoul'nt I press enter after select cards? Or is this a bug?

**Comment by randomflyingtaco** [comment]
Weapons are attached to players instead of heroes to support Majordomo Executus.  It looks like when we made that change, we did not update game_printer.py  I'll put out a patch in a few minutes that should fix that for you.
