### ISSUE TITLE
GIANT is not a minion type

### ISSUE THREAD

**Issue by tonyyyye** [danielyule/hearthbreaker#123]
MINION_TYPE should only include explicit type name. 
Nightmare amalgam defines all other types of minions, which are: 
    Elemental, Mech, Demon, Murloc, Dragon, Beast, Pirate and Totem

GIANT is not a named type, although giants do have common features.

**Comment by tonyyyye** [comment]
All types are now implied by Nightmare Amalgam

**Comment by danielyule** [comment]
Hey,

As you might have noticed, work has pretty much ceased on this project.  I'm happy to accept pull requests, and any contributions, but I don't personally plan to put any work into it in the foreseeable future.  If you're interested, there are a couple of other simulators under active development over at [https://hearthsim.info/](https://hearthsim.info/)

**Comment by tonyyyye** [comment]
Thanks.
