### ISSUE TITLE
unimplemented card list

### ISSUE THREAD

**Issue by zetsubo** [danielyule/hearthbreaker#77]
The project was previously keeping track of unimplemented cards using the old cards.csv file, which seems to have been scrapped in favor of using Hearthstone JSON.

Is there a new list for tracking which cards have been implemented? If not, do you have a format preference if I were to throw something together? I figure I'd just make a wiki page for it.

**Comment by danielyule** [comment]
I think a wiki page is just dandy, if you'd like to create it.  I've got one of my tests printing out a list of cards not yet implemented, which you can see if you run the tests, or if you look at the output on TravisCI, for example: https://travis-ci.org/danielyule/hearthbreaker/jobs/46475557

**Comment by zetsubo** [comment]
Ah cool, just ran tests and saw that output. Thanks!
