### ISSUE TITLE
'int' object is not callable

### ISSUE THREAD

**Issue by Ragowit** [danielyule/hearthbreaker#80]
Deck 1: Dragonling Mechanic, River Crocolisk, Silverback Patriarch, Defender of Argus, Wisp, Bloodlust, Deathlord, Flametongue Totem, Chillwind Yeti, Flametongue Totem, Argent Squire, Deathlord, Frostwolf Warlord, Wolfrider, River Crocolisk, Wolfrider, Azure Drake, Nerub'ar Weblord, Ogre Magi, Fire Elemental, Ironforge Rifleman, Argent Squire, Stormpike Commando, Zombie Chow, Sludge Belcher, Gelbin Mekkatorque, Stormpike Commando, Lord of the Arena, Zombie Chow, Kobold Geomancer

Deck 2: Twisting Nether, Youthful Brewmaster, Bloodmage Thalnos, Feugen, Fen Creeper, Silverback Patriarch, Summoning Portal, Sense Demons, Demolisher, Stranglethorn Tiger, Sludge Belcher, Nightblade, Argent Commander, Coldlight Oracle, Corruption, Young Dragonhawk, Old Murk-Eye, Stoneskin Gargoyle, Nerub'ar Weblord, Wailing Soul, Nightblade, Target Dummy, Kobold Geomancer, Wisp, Razorfen Hunter, Acidic Swamp Ooze, Loatheb, Frost Elemental, Mana Addict, Lord Jaraxxus

```
Traceback (most recent call last):
  File "C:\Users\Ragowit\Documents\GitHub\mcts\hearthbreaker\uct.py", line 140, in DoMove
    self.game.play_card(self.game.current_player.hand[move[3]])
  File "C:\Users\Ragowit\Documents\GitHub\mcts\hearthbreaker\hearthbreaker\game_objects.py", line 2015, in play_card
    card.use(self.current_player, self)
  File "C:\Users\Ragowit\Documents\GitHub\mcts\hearthbreaker\hearthbreaker\game_objects.py", line 909, in use
    minion.battlecry(minion)
TypeError: 'int' object is not callable
```

**Comment by danielyule** [comment]
This was only happening when Jaraxxus made an infernal, then youthful brewmaster brewed it back, and then it was played again.  Anyways, fixed now.
