### ISSUE TITLE
Some effects last too long

### ISSUE THREAD

**Issue by foxor** [danielyule/hearthbreaker#86]
The random AI (using the zoo.hsdeck) used abusive sergeant on one of my minions and the effect lasted until the end of my turn.

hearthbreaker/cards/minions/neutral.py:559
- battlecry=Battlecry(Give(BuffUntil(ChangeAttack(2), TurnEnded())),
+ battlecry=Battlecry(Give(BuffUntil(ChangeAttack(2), TurnEnded(BothPlayer()))),

It looks like there are a bunch more of these.

**Comment by danielyule** [comment]
An excellent catch.  I had actually created a player (CurrentPlayer) specifically for this purpose, and used it for Bestial Wrath, but did not use it for Sergeant or Dark Iron Dwarf (among others).  It's now fixed.
