### ISSUE TITLE
Ogres should not choose a new target unless there is at least one enemy minion present

### ISSUE THREAD

**Issue by danielyule** [danielyule/hearthbreaker#90]

**Comment by anka-213** [comment]
How is this a problem? The current code should work fine, since `ChangeTarget` does nothing unless there are any alternative targets.

    def act(self, actor, target):
        possible_targets = [t for t in self.selector.choose_targets(target, target.current_target)]
        if len(possible_targets) > 0:
            target.current_target = possible_targets[0]

**Comment by danielyule** [comment]
It matters in the case of misdirection.  In HS, if there are no minions and misdirection fires, the ogre will always hit its own hero.  In Hearthbreaker, ChangeTarget will fire because its current target is its own hero, so it will choose the enemy hero.
Also, in case there's ever a minion which does something whenever an effect is triggered, I'd like to have it match up.

**Comment by anka-213** [comment]
What would happen if the enemy hero is immune and there is just one minion? Should the effect still trigger on the Ogre?

**Comment by danielyule** [comment]
I would guess that the effect could trigger.  I'm going to try to test this in the next little while.

Also, if you're interested, we have an ongoing conversation about weird edge cases and such in the #hearthsim irc channel on freenode.net.

**Comment by danielyule** [comment]
Just tested it, the ogre effect goes off even if the hero is immune
