### ISSUE TITLE
Minions that die immediately after a secret is played by Mad Scientist should be duplicated

### ISSUE THREAD

**Issue by danielyule** [danielyule/hearthbreaker#91]
The opponent has a mad scientist and a Sludge Belcher down, played in that order. I kill both at once with a swipe. The mad scientist's deathrattle should go off, and set duplicate.  Then, the duplicate should fire on the death of the Sludge Belcher

**Comment by anka-213** [comment]
It already does, as far as I can see. The test (expected failure) you introduced in 7e2c5a358 has never failed.

**Comment by anka-213** [comment]
This was apparently fixed by 9b7704f. (Assuming that 7e2c5a358 was supposed to be the test for this bug.)

What previously happened was that the Mad Scientist was duplicated instead of the Magma Rager.

**Comment by danielyule** [comment]
Very true, it was fixed.  However, further experimentation indicates that the fix I gave isn't right.  Basically, I can either fix this or #92, but not both.  I'll close this one though, and leave 92.

**Comment by anka-213** [comment]
You might want to remove the "expected failure" from the test as well.

**Comment by danielyule** [comment]
I think I did already?  Unless I am missing something.  https://github.com/danielyule/hearthbreaker/blob/master/tests/card_tests/mage_tests.py#L623

**Comment by anka-213** [comment]
Oh, sorry. :P
