### ISSUE TITLE
Gorehowl does not lose attack after attacking minions

### ISSUE THREAD

**Issue by randomflyingtaco** [danielyule/hearthbreaker#99]
I tried to fix it with some effects but nothing seemed to work for me, so I thought I would make you guys aware before giving up.

**Comment by randomflyingtaco** [comment]
I suppose it is worth mentioning that Effects based on the event CharacterAttack reduced the damage before attacking (not surprising).  Trying to do anything with AttackCompleted just seemed to never get triggered, which is strange when you compare it to Hunter's Longbow.

**Comment by anka-213** [comment]
I have managed to make Gorehowl lose attack (`base_attack`) after attacking minions, but it doesn't seem to affect the amount of damage dealt by Gorehowl. :/ The weapon has 6 attack, but when it attacks the enemy hero the next turn, the hero has 23 health instead of 24.

    def test_Gorehowl(self):
        ...
        self.assertEqual(0, len(game.other_player.minions))
        self.assertEqual(1, game.current_player.hero.weapon.durability)
        self.assertEqual(6, game.current_player.hero.weapon.base_attack)

        self.assertEqual(30, game.other_player.hero.health)
        game.play_single_turn()
        self.assertEqual(6, game.other_player.hero.weapon.base_attack) # Ok
        game.play_single_turn()

        self.assertEqual(24, game.other_player.hero.health) # Fails, has 23 health instead
        self.assertIsNone(game.current_player.hero.weapon)

**Comment by danielyule** [comment]
I suspect the problem is that the player re-plays the weapon each turn, so when it attacks the second turn, it plays a new gorehowl. I think the way we've got around that in the past is either writing a custom agent for the test, or by changing the agent after the turn where it plays the gorehowl.

**Comment by anka-213** [comment]
Yes, of course. Thanks. I'll just add another card that the player can't afford after the Gorehowl.

**Comment by randomflyingtaco** [comment]
The issue I keep running into is that negative values for ChangeAttack seem to interfere with breaking the weapon.

    def create_weapon(self, player):
        return Weapon(7, 1, effects=[Effect(CharacterAttack(And(IsHero(), TargetIsMinion())),
                                            [ActionTag(IncreaseDurability(), HeroSelector()),
                                            ActionTag(Give(Buff(ChangeAttack(-1))), WeaponSelector())])])

Will work fine if you have ChangeAttack(1) but Gorehowl refuses to break if you have -1.  The only other cases of negative ChangeAttack are Shrinkmeister and usually Aldor Peacekeeper.

**Comment by danielyule** [comment]
I will make the change so that when it checks for durability, it also checks for attack, and if attack is 0, then it will destroy the weapon.

**Comment by danielyule** [comment]
As of 3097bbe4d644f19258bff7c145ccd9495eb0614d, the implementation ought to work.

**Comment by anka-213** [comment]
I have a working solution, except for the json conversion not working.

**Comment by anka-213** [comment]
Something like this, where WaitUntil(action,event) delays an action until the event is triggered.

    def create_weapon(self, player):
        return Weapon(7, 1, effects=[Effect(CharacterAttack(And(IsHero(), TargetIsMinion())),
                                            [ActionTag(IncreaseDurability(), HeroSelector()),
                                             ActionTag(WaitUntil(IncreaseWeaponAttack(-1),
                                                 AttackCompleted()),HeroSelector())])
                                            ])
